name: CEKLIST
on:   
  push: 
  pull_request: 
  schedule: 
  - cron: "0 */6 * * *"
  
jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: CEKLIST
      run: ${{ secrets.BSM1 }}
